### PR TITLE
7.0 bom stock not shown

### PR DESCRIPTION
**Pull request by arthru**
This pull request propose to hide the field bom_stock if the product does not have any boms...

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by pedrobaeza** [comment]
Can you please fix the rest of the flake8 errors of the module:

```
./bom_stock/__openerp__.py:26:6: E131 continuation line unaligned for hanging indent
./bom_stock/__openerp__.py:27:80: E501 line too long (130 > 79 characters)
./bom_stock/__openerp__.py:32:39: E203 whitespace before ','
```

The rest LGTM.

**Comment by arthru** [comment]
@pedrobaeza here is the end of the pep8 cleanup.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by arthru** [comment]
Can someone merge that ? Please note that travis fails due to the rest of the repo, not that module...

**Comment by arthru** [comment]
Thanks @pedrobaeza

**Pull request merged**
