### PR TITLE
Initial port to v8 and inclusion of dependent module.  Minor things to address: image, manifest, pdb code, etc

### PR DESCRIPTION
**Pull request by ghost**
Note:  these modules are working, but metadata for bom_stock is not complete.  Sharing to avoid duplication of effort.

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi Ray,

Thanks a lot for the contribution here ! I have some questions/remarks thought :
- Why don't you rely on the stock_available_immediately (https://github.com/OCA/stock-logistics-warehouse/tree/8.0/__unported__/stock_available_immediately) and replace it with ursa_stock_sellable_qty ? Isn't the needed feature already there ?
- I understand that "ursa_stock_sellable_qty" is also changing the warning in the sale process to adapt it to this new "qty_sellable" field. So in the end, it raise a warning about not having enough stock based on this field rather than the standard one,

At the end, my suggestion to be in-line with what already exists in the OCA would be:

  1) Migrate the "stock_available_immediately" (very easy)
  2) Base the bom_stock on it on version 8.0 as it was on version 7.0 to keep the backward compatibility
  3) Create a new module called "sale_sellable_qty_stock_warning" that implement the warning based on " 'immediately_usable_qty" field

What do you (or other) think here ? So for now, I give a :-1: 

Regards,

Joël

**Comment by pedrobaeza** [comment]
Even if ursa_... is still needed, ursa word must be removed.

**Comment by ghost** [comment]
@jgrandguillaume 

I wrote ursa_stock_sellable_quantity before I knew the other module existed.

The change in the way the warning works was a requirement of the customer funding the module.

I have no problem with your suggestions.

@pedrobaeza 

I am not responsible for naming modules at Ursa and have no problem with this change.

P.S.  I shared this module via a PR because I wanted to avoid duplication of efforts and contribute.  I don't have the time to converse and contribute further and am happy for the community to take over from here.

**Comment by clonedagain** [comment]
The way the warning is done here worries me a bit - I suppose it's mostly copied/pasted ("whitebox reuse") from the standard sale_stock module.
I did it this way in v5/v6 but it's a pain to maintain. That's why I looked for a less intrusive way to do this, using a small context trick in this PR: https://github.com/OCA/stock-logistics-warehouse/pull/25.

@jgrandguillaume I can probably propose a separate module for the warning code, when I migrate it to v8 (probably later this year).
I can do it either like @rcarnes or like in my initial PR, depending on what everyone prefers.
Any advice?

**Comment by yvaucher** [comment]
@rcarnes First commit is not well authored:
https://github.com/ursainfosystems/product-kitting/commit/35ab74798f374388268719ff8fa835b1807e966c
Please make sure to push it from a station on which you configured correctly author name and author email.

Can be fixed by `git commit --amend --author"Name <email>` then `git push -f`

**Comment by ghost** [comment]
@yvaucher 

I added the email address to my account and now https://github.com/ursainfosystems/product-kitting/commit/35ab74798f374388268719ff8fa835b1807e966c shows authorship in my name

Is that resolved now ?

**Comment by yvaucher** [comment]
@rcarnes Much better, thanks

**Comment by pedrobaeza** [comment]
This includes forbidden module name (with company in it), and very old. If you are still interested, feel free to reopen a new PR.

**Pull request closed without merging**
