### PR TITLE
[REM] removed bom_stock from version 9.0

### PR DESCRIPTION
**Pull request by SodexisTeam**
Removed bom_stock module from 9.0 as per discussion in https://github.com/OCA/product-kitting/pull/11/

cc: @OSguard @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by gurneyalex** [comment]
I'd go for deprecation rather than blunt removal.

**Comment by pedrobaeza** [comment]
But in this branch removing it is like deprecated it.

**Comment by atchuthan** [comment]
@gurneyalex This module is not available in both 8.0 and 9.0 versions.  Also, we can make a note in https://github.com/OCA/product-kitting/issues/10 as bom_stock functionality is available in https://github.com/OCA/stock-logistics-warehouse/tree/9.0/stock_available_mrp.

If we don't remove this module, OCA might have multiple module names that do the same job.  Thus, duplication of work happens to other OCA members.

**Comment by gurneyalex** [comment]
oh sorry, too many things in my head... 
 :+1: of course, then.

**Pull request merged**
