### PR TITLE
[REM] removed bom_stock from version 8.0

### PR DESCRIPTION
**Pull request by SodexisTeam**
Removed bom_stock module from 8.0 as per discussion in https://github.com/OCA/product-kitting/pull/11/

cc: @OSguard @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by gurneyalex** [comment]
I'd go for deprecation rather than blunt removal.

**Comment by gurneyalex** [comment]
:+1:

**Comment by OSguard** [comment]
bom_split and is child can also be removed as this is core feature in v8+

**Comment by gurneyalex** [comment]
@OSguard see #14 and #15

**Pull request merged**
