### PR TITLE
Correct pep8 errors in the repository

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by yvaucher** [comment]
Almost done:

```
./bom_split/__init__.py:24:1: W391 blank line at end of file
./purchase_bom_split/__init__.py:23:1: W391 blank line at end of file
./sale_bom_split/__init__.py:23:1: W391 blank line at end of file
```

**Comment by guewen** [comment]
@yvaucher done, amended the commit

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: 

Travis errors are not from PEP8

**Comment by StefanRijnhart** [comment]
:+1:

**Pull request merged**
